spring.application.name=OTP-Service

server.port=4567

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harishkavuru4030@gmail.com
spring.mail.password=fben sbxb thhx mcei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
